version: 2
jobs:
  checkout_and_test:
    docker:
      - image: circleci/node:8-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-deps-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - v2-npm-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v2-npm-deps-{{ .Branch }}
            - v2-npm-deps-
      - run:
          name: install NPM dependencies
          command: |
            echo -e "//registry.npmjs.org/:_authToken=$NPM_TOKEN\nscope=@oneflow" > .npmrc
            npm install
      - save_cache:
          key: v2-npm-deps-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: build
          command: |
            npm run build
    # - run:
    #     name: serve
    #     command: |
    #       sudo npm install -g serve
    #       serve -p 3001 dist/
    #     background: true
      - run:
          name: test
          command: |
            npm run test
    # skip until nightwatch vulnerabilities are sorted
    #   - run:
    #       name: audit
    #       command: |
    #         sudo npm install -g npm
    #         npm audit
      - save_cache:
          key: v1-source-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~

  push_image:
    docker:
      - image: circleci/node:8-stretch
    steps:
      - setup_remote_docker
      - restore_cache:
          key: v1-source-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: build
          command: |
            docker build -t oneflow/$CIRCLE_PROJECT_REPONAME .
            docker tag oneflow/$CIRCLE_PROJECT_REPONAME oneflow/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag oneflow/$CIRCLE_PROJECT_REPONAME oneflow/$CIRCLE_PROJECT_REPONAME:`grep '"version"' package.json | egrep -o "[0-9]+.[0-9]+.[0-9]+"`
            fi
      - run:
          name: push
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push oneflow/$CIRCLE_PROJECT_REPONAME
  bump_version:
    docker:
      - image: circleci/node:8-stretch
    steps:
      - restore_cache:
          key: v1-source-{{ .Environment.CIRCLE_SHA1 }}
      - add_ssh_keys
      - run:
          name: Add github to known_hosts
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: tag and patch version
          command: |
            git config --global user.email "circleci@oneflowsystems.com"
            git config --global user.name "Circle CI"
            git reset --hard HEAD
            git tag "v`grep '"version"' package.json | egrep -o "[0-9]+.[0-9]+.[0-9]+"`"
            git push --tags
            # checkout development and bump the version
            git checkout -b circle-ci-version-bump origin/development
            git pull
            npm --no-git-tag-version version patch
            git add package.json package-lock.json
            git commit -m "`grep '"version"' package.json | egrep -o "[0-9]+.[0-9]+.[0-9]+"`"
            git push -u origin circle-ci-version-bump:development --follow-tags
            # checkout master again and delete our local branch
            git checkout master
            git branch -D circle-ci-version-bump
workflows:
  version: 2
  build_and_publish:
    jobs:
      - checkout_and_test:
          context: oneflow
      - push_image:
          context: oneflow
          requires:
            - checkout_and_test
          filters:
            branches:
              only:
                - development
                - master
      - bump_version:
          context: oneflow
          requires:
            - push_image
          filters:
            branches:
              only: master
